### ISSUE TITLE
'QVBoxLayout' object has no attribute 'setMargin'

### ISSUE THREAD

**Issue by ctheissen** [BU-hammerTeam/PyHammer#14]
Okay, new issue:

ctheissen$ python3 pyhammer.py 
Traceback (most recent call last):
  File "pyhammer.py", line 1032, in <module>
    PyHammerSettingsGui(options)
  File "pyhammer.py", line 253, in __init__
    self.configureGui()     # Configure the GUI component settings
  File "pyhammer.py", line 577, in configureGui
    self.grid.setMargin(2)
AttributeError: 'QVBoxLayout' object has no attribute 'setMargin'

No idea what this one is.
I'm using a Mac with Python 3.6.1 with PyQt5 5.8.1.1

I think this is an issue with a deprecated attribute.

**Comment by zephyr5050** [comment]
Turns out it is depreciated in qt5. `setMargin(2)` should be replaced with `setContentsMargin(2,2,2,2)`.

Updated developer branch with changes that should fix that. I managed to get this running in a qt5 version I had. Try updating and see what you get. Hopefully there won't be any more issues that prevent you from actually running the code in qt5.
