### ISSUE TITLE
Need to mask out the bad pixel at ~5600 Ang

### ISSUE THREAD

**Issue by ctheissen** [BU-hammerTeam/PyHammer#16]
There is a bad or hot pixel in a lot of the spectra at around 5600 Angstroms. This feature tends to take control of the y-limits of the plot, and is very distracting. I would advise masking this feature from the spectra where it is an issue.

**Comment by zephyr5050** [comment]
I believe you're referring to the stitching spike that appears in the SDSS spectra. There is an option in the Options menu "Remove SDSS Stitch Spike" (or Ctrl-R) that will remove this spike. This spike does appear in some of the templates as well, and we'll look into seeing about changing that if we can.

We don't remove this by default because the idea we were going for was that we didn't want to modify the user's spectrum without their knowledge. We wanted the user to be able to choose if their spectrum gets changed in some way, so they're completely sure of what changes are applied to it.

**Comment by ctheissen** [comment]
It doesn't appear to work. I still get the spike.

**Comment by zephyr5050** [comment]
As far as I can tell from experimentation, the "Remove SDSS Stitch Spike" works for me on a variety of platforms. I'm closing this issue, but will re-open it if someone has an example of it not working for them and can provide some more specific information that can be used to debug.
